### ISSUE TITLE
REACT NATIVE MODULES

### ISSUE THREAD

**Issue by suulcoder** [suulcoder/InsideMaps#2]
Hola a todos. tengo un problema para correr el programa en el teléfono, en web funciona perfecto, y antes estaba funcionando perfecto en el teléfono, pero al hacer el pull, me tira el siguiente error:

node_modules/react-native/Libraries/Image/ImageBackground.js: /home/thecoder/Documentos/UVG/Software/InsideMaps/node_modules/react-native/Libraries/Image/ImageBackground.js: Missing class properties transform.
  48 |   }
  49 | 
> 50 |   _viewRef: ?React.ElementRef<typeof View> = null;
     |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  51 | 
  52 |   _captureRef = ref => {
  53 |     this._viewRef = ref;

Intente componiendo el package.json o restaurando una versión vieja, pero no esta funcionando y no se que hacer, por si alguien encuentra como hacerlo por favor

**Comment by gusmendez99** [comment]
React Native module was excluded from this repo
